server:
  port: 8099
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:~/.kuku/db/qd
    username: qd
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      settings:
        web-allow-others: true
    path: /h2
    enabled: true
user:
  #添加挂机手机号的最大值
  max: 600
  #懒得用数据库了，用数据库我还要写后台，我懒
  htmlCon:
    #标题
    title: 撸流量
    #抽奖挂机上面的红色字
    lotteryText: 不需要百度ai啦。
    #底部版权说明
    copyright: <a target="_blank" href="https://github.com/kukume/unicom">GitHub</a>，By <a target="_blank" href="https://www.kuku.me">kuku</a>，<a href="http://beian.miit.gov.cn" target="_blank">湘ICP备19013011号</a>
    #小图标链接
    ico: https://www.kuku.me/favicon.ico
  #定时器，此为每天的00:01运行
  cron: 0 1 0 * * ?
  #支持多个key，每个key调用199次切换下一个。
  #不需要使用这个了。。
  key:
    - apiKey: FFinlR9wBTwkRiSG225N64tL
      secretKey: QlLI3Giq2lQjpai9Kmsk6q2d8CAWMNlG
#    - apiKey: xxx
#      secretKey: xxx
#    - apiKey: xxx
#      secretKey: xxx
#    - apiKey: xxx
#      secretKey: xxx
