server:
  port: 8099
spring:
  ##如使用h2数据库注释mysql部分
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kuku?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  ##如使用h2数据库注释mysql部分
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  thymeleaf:
    cache: false
    ##如使用mysql数据库注释h2部分
#  datasource:
#    url: jdbc:h2:~/.kuku/db/qd
#    username: qd
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      settings:
#        web-allow-others: true
#      path: /console
#      enabled: true
    ##如使用mysql数据库注释h2部分
user:
  #添加挂机手机号的最大值
  max: 600
  #懒得用数据库了，用数据库我还要写后台，我懒
  htmlCon:
    #标题
    title: 青岛啤酒
    #抽奖挂机上面的红色字
    lotteryText:
    #底部版权说明
    copyright: <a target="_blank" href="https://github.com/kukume/unicom">GitHub</a>，By <a target="_blank" href="https://www.kuku.me">kuku</a>，<a href="http://beian.miit.gov.cn" target="_blank">湘ICP备19013011号</a>
    #小图标链接
    ico: https://www.kuku.me/favicon.ico
  #定时器
  #此为每天的00:01运行
  cron: 0 20 0 * * ?